=== Antonio070722/Lenguaje_marcas/Ejercicios/WorkShop XML/libros.dtd
<!--Ejercicio2-->
<!--Que pueda haber mas de un elemento libro:-->
<!ELEMENT libros (libro+)>

<!--El orden de los elementos en libro-->
<!ELEMENT libro (titulo, autor, año, precio)>

<!--Ejercicio3-->
<!--Cada libro tiene que tener un atributo isbn-->
<!ATTLIST libro
    isbn CDATA #REQUIRED
>


<!--Que sea texto el contenido de cada elemento-->
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT precio (#PCDATA)>

=== Antonio070722/Lenguaje_marcas/Ejercicios/WorkShop XML/libros.xml
<?xml version="1.0">
<!DOCTYPE libros SYSTEM "libros.dtd">
<!--Ejercicio1-->
<libros>
<!--Ejercicio 3: añadidos los isbn, en el dtd he puesto que sea obligatorio,-->
    <libro isbn="0000">
        <titulo>El Quijote</titulo>
        <autor>Miguel de Cervantes</autor>
        <año>1605</año>
        <precio>19.99</precio>
    </libro>
    <libro isbn="0000">
        <titulo>La celestina</titulo>
        <autor>Fernando de Rojas</autor>
        <año>1499</año>
        <precio>14.99</precio>
    </libro>
    <libro isbn="0000">
        <titulo>Don Juan Tenorio</titulo>
        <autor>José Zorrilla</autor>
        <año>1844</año>
        <precio>9.99</precio>
    </libro>
</libros>
